/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAirbnbRouteImport } from './routes/_authenticated/airbnb'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedCommissionsRouteImport } from './routes/_authenticated/commissions'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedConstructionRouteImport } from './routes/_authenticated/construction'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDisbursementsRouteImport } from './routes/_authenticated/disbursements'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedForcePasswordChangeRouteImport } from './routes/_authenticated/force-password-change'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedLeasesRouteImport } from './routes/_authenticated/leases'
import { Route as AuthenticatedLicencesRouteImport } from './routes/_authenticated/licences'
import { Route as AuthenticatedListingsRouteImport } from './routes/_authenticated/listings'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedRefundsRouteImport } from './routes/_authenticated/refunds'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthenticatedVerificationRouteImport } from './routes/_authenticated/verification'
import { Route as AuthenticatedInvoicesInvoiceIdPrintRouteImport } from './routes/_authenticated/invoices_.$invoiceId.print'
import { Route as AuthenticatedLeasesLeaseIdStatementRouteImport } from './routes/_authenticated/leases_.$leaseId.statement'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAirbnbRoute = AuthenticatedAirbnbRouteImport.update({
  id: '/airbnb',
  path: '/airbnb',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommissionsRoute =
  AuthenticatedCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConstructionRoute =
  AuthenticatedConstructionRouteImport.update({
    id: '/construction',
    path: '/construction',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisbursementsRoute =
  AuthenticatedDisbursementsRouteImport.update({
    id: '/disbursements',
    path: '/disbursements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForcePasswordChangeRoute =
  AuthenticatedForcePasswordChangeRouteImport.update({
    id: '/force-password-change',
    path: '/force-password-change',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeasesRoute = AuthenticatedLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLicencesRoute = AuthenticatedLicencesRouteImport.update({
  id: '/licences',
  path: '/licences',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListingsRoute = AuthenticatedListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRefundsRoute = AuthenticatedRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerificationRoute =
  AuthenticatedVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdPrintRoute =
  AuthenticatedInvoicesInvoiceIdPrintRouteImport.update({
    id: '/invoices_/$invoiceId/print',
    path: '/invoices/$invoiceId/print',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeasesLeaseIdStatementRoute =
  AuthenticatedLeasesLeaseIdStatementRouteImport.update({
    id: '/leases_/$leaseId/statement',
    path: '/leases/$leaseId/statement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/airbnb': typeof AuthenticatedAirbnbRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/construction': typeof AuthenticatedConstructionRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disbursements': typeof AuthenticatedDisbursementsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/force-password-change': typeof AuthenticatedForcePasswordChangeRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/leases': typeof AuthenticatedLeasesRoute
  '/licences': typeof AuthenticatedLicencesRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/map': typeof AuthenticatedMapRoute
  '/members': typeof AuthenticatedMembersRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/refunds': typeof AuthenticatedRefundsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/invoices/$invoiceId/print': typeof AuthenticatedInvoicesInvoiceIdPrintRoute
  '/leases/$leaseId/statement': typeof AuthenticatedLeasesLeaseIdStatementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/airbnb': typeof AuthenticatedAirbnbRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/construction': typeof AuthenticatedConstructionRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disbursements': typeof AuthenticatedDisbursementsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/force-password-change': typeof AuthenticatedForcePasswordChangeRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/leases': typeof AuthenticatedLeasesRoute
  '/licences': typeof AuthenticatedLicencesRoute
  '/listings': typeof AuthenticatedListingsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/map': typeof AuthenticatedMapRoute
  '/members': typeof AuthenticatedMembersRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/refunds': typeof AuthenticatedRefundsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/invoices/$invoiceId/print': typeof AuthenticatedInvoicesInvoiceIdPrintRoute
  '/leases/$leaseId/statement': typeof AuthenticatedLeasesLeaseIdStatementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/airbnb': typeof AuthenticatedAirbnbRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/commissions': typeof AuthenticatedCommissionsRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/construction': typeof AuthenticatedConstructionRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disbursements': typeof AuthenticatedDisbursementsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/force-password-change': typeof AuthenticatedForcePasswordChangeRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/leases': typeof AuthenticatedLeasesRoute
  '/_authenticated/licences': typeof AuthenticatedLicencesRoute
  '/_authenticated/listings': typeof AuthenticatedListingsRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/refunds': typeof AuthenticatedRefundsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/_authenticated/verification': typeof AuthenticatedVerificationRoute
  '/_authenticated/invoices_/$invoiceId/print': typeof AuthenticatedInvoicesInvoiceIdPrintRoute
  '/_authenticated/leases_/$leaseId/statement': typeof AuthenticatedLeasesLeaseIdStatementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/privacy'
    | '/terms'
    | '/activity'
    | '/airbnb'
    | '/analytics'
    | '/audit'
    | '/backup'
    | '/branches'
    | '/commissions'
    | '/companies'
    | '/construction'
    | '/crm'
    | '/dashboard'
    | '/disbursements'
    | '/documents'
    | '/employees'
    | '/finance'
    | '/force-password-change'
    | '/integrations'
    | '/invoices'
    | '/leases'
    | '/licences'
    | '/listings'
    | '/maintenance'
    | '/map'
    | '/members'
    | '/onboarding'
    | '/plans'
    | '/pricing'
    | '/properties'
    | '/refunds'
    | '/reports'
    | '/roadmap'
    | '/roles'
    | '/sales'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/tenants'
    | '/transactions'
    | '/units'
    | '/verification'
    | '/invoices/$invoiceId/print'
    | '/leases/$leaseId/statement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/privacy'
    | '/terms'
    | '/activity'
    | '/airbnb'
    | '/analytics'
    | '/audit'
    | '/backup'
    | '/branches'
    | '/commissions'
    | '/companies'
    | '/construction'
    | '/crm'
    | '/dashboard'
    | '/disbursements'
    | '/documents'
    | '/employees'
    | '/finance'
    | '/force-password-change'
    | '/integrations'
    | '/invoices'
    | '/leases'
    | '/licences'
    | '/listings'
    | '/maintenance'
    | '/map'
    | '/members'
    | '/onboarding'
    | '/plans'
    | '/pricing'
    | '/properties'
    | '/refunds'
    | '/reports'
    | '/roadmap'
    | '/roles'
    | '/sales'
    | '/settings'
    | '/subscriptions'
    | '/support'
    | '/tenants'
    | '/transactions'
    | '/units'
    | '/verification'
    | '/invoices/$invoiceId/print'
    | '/leases/$leaseId/statement'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/privacy'
    | '/terms'
    | '/_authenticated/activity'
    | '/_authenticated/airbnb'
    | '/_authenticated/analytics'
    | '/_authenticated/audit'
    | '/_authenticated/backup'
    | '/_authenticated/branches'
    | '/_authenticated/commissions'
    | '/_authenticated/companies'
    | '/_authenticated/construction'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/disbursements'
    | '/_authenticated/documents'
    | '/_authenticated/employees'
    | '/_authenticated/finance'
    | '/_authenticated/force-password-change'
    | '/_authenticated/integrations'
    | '/_authenticated/invoices'
    | '/_authenticated/leases'
    | '/_authenticated/licences'
    | '/_authenticated/listings'
    | '/_authenticated/maintenance'
    | '/_authenticated/map'
    | '/_authenticated/members'
    | '/_authenticated/onboarding'
    | '/_authenticated/plans'
    | '/_authenticated/pricing'
    | '/_authenticated/properties'
    | '/_authenticated/refunds'
    | '/_authenticated/reports'
    | '/_authenticated/roadmap'
    | '/_authenticated/roles'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/subscriptions'
    | '/_authenticated/support'
    | '/_authenticated/tenants'
    | '/_authenticated/transactions'
    | '/_authenticated/units'
    | '/_authenticated/verification'
    | '/_authenticated/invoices_/$invoiceId/print'
    | '/_authenticated/leases_/$leaseId/statement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/airbnb': {
      id: '/_authenticated/airbnb'
      path: '/airbnb'
      fullPath: '/airbnb'
      preLoaderRoute: typeof AuthenticatedAirbnbRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commissions': {
      id: '/_authenticated/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AuthenticatedCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/construction': {
      id: '/_authenticated/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof AuthenticatedConstructionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disbursements': {
      id: '/_authenticated/disbursements'
      path: '/disbursements'
      fullPath: '/disbursements'
      preLoaderRoute: typeof AuthenticatedDisbursementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/force-password-change': {
      id: '/_authenticated/force-password-change'
      path: '/force-password-change'
      fullPath: '/force-password-change'
      preLoaderRoute: typeof AuthenticatedForcePasswordChangeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leases': {
      id: '/_authenticated/leases'
      path: '/leases'
      fullPath: '/leases'
      preLoaderRoute: typeof AuthenticatedLeasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licences': {
      id: '/_authenticated/licences'
      path: '/licences'
      fullPath: '/licences'
      preLoaderRoute: typeof AuthenticatedLicencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings': {
      id: '/_authenticated/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AuthenticatedListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refunds': {
      id: '/_authenticated/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof AuthenticatedRefundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verification': {
      id: '/_authenticated/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AuthenticatedVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices_/$invoiceId/print': {
      id: '/_authenticated/invoices_/$invoiceId/print'
      path: '/invoices/$invoiceId/print'
      fullPath: '/invoices/$invoiceId/print'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leases_/$leaseId/statement': {
      id: '/_authenticated/leases_/$leaseId/statement'
      path: '/leases/$leaseId/statement'
      fullPath: '/leases/$leaseId/statement'
      preLoaderRoute: typeof AuthenticatedLeasesLeaseIdStatementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAirbnbRoute: typeof AuthenticatedAirbnbRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCommissionsRoute: typeof AuthenticatedCommissionsRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedConstructionRoute: typeof AuthenticatedConstructionRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisbursementsRoute: typeof AuthenticatedDisbursementsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedForcePasswordChangeRoute: typeof AuthenticatedForcePasswordChangeRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedLeasesRoute: typeof AuthenticatedLeasesRoute
  AuthenticatedLicencesRoute: typeof AuthenticatedLicencesRoute
  AuthenticatedListingsRoute: typeof AuthenticatedListingsRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedRefundsRoute: typeof AuthenticatedRefundsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
  AuthenticatedVerificationRoute: typeof AuthenticatedVerificationRoute
  AuthenticatedInvoicesInvoiceIdPrintRoute: typeof AuthenticatedInvoicesInvoiceIdPrintRoute
  AuthenticatedLeasesLeaseIdStatementRoute: typeof AuthenticatedLeasesLeaseIdStatementRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAirbnbRoute: AuthenticatedAirbnbRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCommissionsRoute: AuthenticatedCommissionsRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedConstructionRoute: AuthenticatedConstructionRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisbursementsRoute: AuthenticatedDisbursementsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedForcePasswordChangeRoute: AuthenticatedForcePasswordChangeRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedLeasesRoute: AuthenticatedLeasesRoute,
  AuthenticatedLicencesRoute: AuthenticatedLicencesRoute,
  AuthenticatedListingsRoute: AuthenticatedListingsRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedRefundsRoute: AuthenticatedRefundsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
  AuthenticatedVerificationRoute: AuthenticatedVerificationRoute,
  AuthenticatedInvoicesInvoiceIdPrintRoute:
    AuthenticatedInvoicesInvoiceIdPrintRoute,
  AuthenticatedLeasesLeaseIdStatementRoute:
    AuthenticatedLeasesLeaseIdStatementRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
